sidekick:
  apiKey: <YOUR-API-KEY>
  agent:
    broker:
      host: wss://broker.service.runsidekick.com
    log:
      level: debug
    application:
      name: sidekick-demo-todo-app-java
      stage: onboarding
      version: 1.0.0